stages:
  - build
  - deploy

# 编译
build:
  stage: build
  image: ponycool/php-docker-8.2:latest
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - composer install
  script:
    # docker in docker跨平台编译遇到无法解决的错误，暂时使用手动编译
    - docker build -t "$DOCKER_IMAGE_NAME" .
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
    - |
      if echo "$CI_COMMIT_TAG" | grep -Eq '^v[0-9]+\.[0-9]+'; then
        echo "This is a release"
      fi
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

# 部署
deploy:
  stage: deploy
  image: alpine
  before_script:
    - 'which ssh-agent || ( apk update && apk add openssh-client git )'
    - eval $(ssh-agent -s)
    - echo "$DEMO_SERVER_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $DEMO_SERVER_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh root@$DEMO_SERVER_HOST
      "docker ps \
      && docker images"
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

